name: build examples
on: [push, pull_request]
jobs:
  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Compile examples
        run: |
          cd examples
          ./compile.sh
